name: CI 
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v3
    - name: install 
      run:  docker-compose down

  Test:
    needs: Build
    runs-on: self-hosted
    steps:
    - name: test 
      run: sleep 10 && curl 52.201.162.71
      
  Package:
   needs: Test
   runs-on: self-hosted
   steps:
   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    
